### ISSUE TITLE
Crash or possible mod incompatibility? 

### ISSUE THREAD

**Issue by TheeMrCheeky** [SilentChaos512/Power-Scale#1]
[crash-2024-12-09_14.35.59-fml.txt](https://github.com/user-attachments/files/18068050/crash-2024-12-09_14.35.59-fml.txt)

Neoforge 21.1.85

![image](https://github.com/user-attachments/assets/047f73d8-c6d9-4e95-9fee-0cac4da5682b)

**Comment by SilentChaos512** [comment]
Looks like a build error. Should be easy to fix.
