### ISSUE TITLE
Crash on using search box

### ISSUE THREAD

**Issue by ruax2891** [SilentChaos512/Power-Scale#2]
## Versions

- **Power Scale**: 0.1.3
- **Silent Lib**: 10.3.0
- **NeoForge**: 21.1.89
- **Modpack**: Private Modpack 

## Expected Behavior

I'm able to search items as normal

## Actual Behavior

Upon trying to search something in the creative inventory, the game freezes and crashes.

## Links/Images

- https://mclo.gs/f0k41LA

## Steps to Reproduce the Problem

1. Get into creative mode
2. Go into the search bar and try to search for an item
3. Crash

If you need any more info, let me know, I don't usually write issues so I'm not great at them

**Comment by SilentChaos512** [comment]
This is odd... It's like your instance of Minecraft is not loading the scaling attribute system. There's no mention of it in the log file. I could add some checks into my code to prevent the crash, but that wouldn't fix the root of the problem, whatever that may be.

**Comment by ruax2891** [comment]
Hey, yeah my instance is pretty buggy and I'm constantly fighting against it, I don't know what mod could be causing this but if I ever get any more info I'll let you know
I just thought of submitting an issue here because it might actually be the mod lol
Thanks for the info though!!

**Comment by ruax2891** [comment]
Hey, decided to close this since I gave up on fixing the modpack, couldn't fix a constant crash and I'm guessing the initial error for this issue was from another mod (which I also couldn't find lol)
Thanks for the help!
